apiVersion: skaffold/v3
kind: Config
deploy:
  kubectl: {}

manifests:
 rawYaml:
 - ./infra/k8s/*

build:
  local:
    push: false
  artifacts:
    - image: krniya/not-auth
      context: auth
      docker:
        dockerfile: Dockerfile
        noCache: false
        pullParent: false
        squash: false
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
    - image: krniya/not-workspace
      context: workspace
      docker:
        dockerfile: Dockerfile
        noCache: false
        pullParent: false
        squash: false
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
    - image: krniya/not-folder
      context: folder
      docker:
        dockerfile: Dockerfile
        noCache: false
        pullParent: false
        squash: false
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
    - image: krniya/not-client
      context: client
      docker:
        dockerfile: Dockerfile
        noCache: false
        pullParent: false
        squash: false
      sync:
        manual:
          - dest: .
            src: 'src/**/*.tsx'
    

